name: hematol-chall-22
dependencies:
  - python=3.9
  - tqdm
  - imageio
  - matplotlib
  - scikit-learn
  - cudatoolkit=11.3
  - pandas
  - click
  - pip
  - pip:
      - e2cnn
      - torch==1.11.0
      - torchvision==0.12.0